/*
 * Rules
 *
 * / Rules represents API that is responsible for gathering rules and their statuses.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Rule struct {

	Recording *RecordingRule `json:"recording,omitempty"`

	Alert *Alert `json:"alert,omitempty"`
}
