/*
 * Rules
 *
 * / Rules represents API that is responsible for gathering rules and their statuses.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RecordingRule struct {
	Name string `json:"name,omitempty"`
	Query string `json:"query,omitempty"`
	Labels *ZLabelSet `json:"labels,omitempty"`
	Health string `json:"health,omitempty"`
	LastError string `json:"last_error,omitempty"`
	EvaluationDurationSeconds float64 `json:"evaluation_duration_seconds,omitempty"`
	LastEvaluation string `json:"last_evaluation,omitempty"`
}
