/*
 * Rules
 *
 * / Rules represents API that is responsible for gathering rules and their statuses.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AlertInstance struct {
	Labels *ZLabelSet `json:"labels,omitempty"`
	Annotations *ZLabelSet `json:"annotations,omitempty"`
	State int32 `json:"state,omitempty"`
	ActiveAt string `json:"active_at,omitempty"`
	Value string `json:"value,omitempty"`
	// Thanos specific. Used mainly for alert API purposes.
	PartialResponseStrategy int32 `json:"PartialResponseStrategy,omitempty"`
}
